### ISSUE TITLE
[prometheus] Make alerts-receiver's ALERTS_QUEUE_LENGTH bigger or adjustable

### ISSUE THREAD

**Issue by meatuses** [deckhouse/deckhouse#7608] opened 2024-02-22 15:22 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Current `ALERTS_QUEUE_LENGTH` variable for `alerts-receiver` is only 100. It can be adjusted only temporarily.

There are big staging clusters with a lot of recurrent alerts like `TargetDown` which can legitimately have more than 100 alerts at the same time. In that case `alerts-receiver` becomes not ready and causes an alert.

### Proposed Solution

Make it bigger (e.g 200) or adjustable in configuration.

**Comment by ArDark-Flant** [comment] 2024-02-22 15:28
additional info:
When one cluster have many `namespaces` and there resouces is duplicate itself ( example 20 test stands ) same deployment can generate x20 records in  `alerts-receiver` which easily fullfill queue and generate alert.

**Comment by konstantin-axenov** [comment] 2024-03-04 07:47
Closed as duplicate of https://github.com/deckhouse/deckhouse/issues/6990

**Closed by konstantin-axenov** 2024-03-04 07:47 UTC
Labels: area/monitoring, type/enhancement, status/needs-triage
