### ISSUE TITLE
[cloud-provider-*] add etcdDisk disk size control for all clouds 

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#5045] opened 2023-06-27 09:40 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

In some clouds the performance of disks depends on their size.

### Proposed Solution

Extend the change from aws to all other clouds 

### Additional Information

https://flant.slack.com/archives/CM1SV46JF/p1687267075922139

**Comment by konstantin-axenov** [comment] 2023-07-03 07:59
Duplicate of https://github.com/deckhouse/deckhouse/issues/3348

**Closed by konstantin-axenov** 2023-07-03 07:59 UTC
Labels: type/enhancement, status/needs-triage
