### ISSUE TITLE
[dhctl] bootstrap ssh tunnel preflight check doesn't work correct with AllowTcpForwarding on remote machine

### ISSUE THREAD

**Issue by Beastlex** [deckhouse/deckhouse#6958] opened 2023-12-20 08:51 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v.1.54.6

### Expected Behavior

Full bootstrap of new cluster or fail on preflight check with message like this "ssh tunnel doesn't work"

### Actual Behavior

1. Preflight checks are passed with `dhctl bootstrap...`
2. First stage of bootstrap is completed
3. But step `Waiting for Kubernetes API to become Ready` is failed with error `Error: kubernetes API is not Ready: Get "http://localhost:22322/version": read tcp 127.0.0.1:40020->127.0.0.1:22322: read: connection reset by peer - error from a previous attempt: read tcp 127.0.0.1:40016->127.0.0.1:22322: read: connection reset by peer`

### Steps To Reproduce

1. On remote machine edit /etc/ssh/sshd_config with
`AllowTcpForwarding = no`
2. Try bootstrap cluster to remote machine with step-by-step [guide](https://deckhouse.io/gs/bm/step4.html) 

### Additional Information

When

**Comment by konstantin-axenov** [comment] 2023-12-20 11:35
Closed as duplicate of https://github.com/deckhouse/deckhouse/issues/6959

**Closed by konstantin-axenov** 2023-12-20 11:35 UTC
Labels: type/bug, area/cli, status/needs-triage
