### ISSUE TITLE
Problems with installation in a managed cluster

### ISSUE THREAD

**Issue by kmkuprienko** [deckhouse/deckhouse#1707] opened 2022-06-03 13:11 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.31

### Expected Behavior

I expected that there would be no alerts.

### Actual Behavior

Hi!
I've installed deckhouse on a GKE cluster. After installation was completed, I've got an alert from prometheus that the storage class created by GKE is not supported by the Deckhouse. I believe that when I install Deckhouse into some managed Kubernetes in the cloud, I would rather have not received any alerts regarding entities that were created by that cloud and not by Deckhouse itself.

### Steps To Reproduce

1. Create a GKE cluster
2. Install Deckhouse

**Comment by nabokihms** [comment] 2022-06-03 13:32
@kmkuprienko the problem is related to this epic https://github.com/deckhouse/deckhouse/issues/1643 and will be fixed in release v1.33

**Closed** 2023-01-01 12:54 UTC
Labels: type/bug, status/rotten, priority/backlog
