### ISSUE TITLE
[cloud-provider-aws] Termination protection for master (static?) nodes

### ISSUE THREAD

**Issue by Ivelok** [deckhouse/deckhouse#3325] opened 2022-12-15 08:10 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There is a possibility of deleting master nodes via AWS-CLI/AWS-UI. 

### Proposed Solution

To protect yourself from this, you can hang the termination protection option on the master nodes. And it probably makes sense to add this option for all static node groups?

**Comment by konstantin-axenov** [comment] 2022-12-15 08:14
Closed as duplicate of https://github.com/deckhouse/deckhouse/issues/3326

**Closed by konstantin-axenov** 2022-12-15 08:14 UTC
Labels: type/enhancement, status/needs-triage
