### ISSUE TITLE
[log-shipper] Add debug log setting

### ISSUE THREAD

**Issue by gyrter** [deckhouse/deckhouse#318] opened 2021-11-24 12:26 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Sometimes we have to enable debug logging in Vector to see co-routine results. 

### Proposed Solution

Add switch to enable debug mode into module config

**Comment by nabokihms** [comment] 2022-03-21 05:53
Closed as a duplicate of https://github.com/deckhouse/deckhouse/issues/396

**Closed by nabokihms** 2022-03-21 05:53 UTC
Labels: priority/backlog
