### ISSUE TITLE
[dhctl] debian 11 - bootstrap.sh: execute on remote: exit status 127

### ISSUE THREAD

**Issue by dezzzm** [deckhouse/deckhouse#2919] opened 2022-10-31 09:40 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

1.38.4

### Expected Behavior

Successful completion "dhctl bootstrap"

### Actual Behavior

dhctl bootstrap result:
│ ┌ bootstrap.sh
│ └ bootstrap.sh (3.30 seconds) FAILED
└ ⛵️ ~ Bootstrap: Initial bootstrap (3.30 seconds) FAILED
run /tmp/candi-bundle-060901586/bootstrap/bootstrap.sh: execute on remote: exit status 127

In VM created file /tmp/bootstrap.sh

### Steps To Reproduce

https://deckhouse.io/ru/gs/bm/step4.html
Bare metal. virtual machine with debian 11 installed.

Run:
dhctl bootstrap --ssh-user=test34 --ssh-host=<master_ip> --ssh-agent-private-keys=/tmp/.ssh/id_rsa \
  --config=/config.yml --ask-become-pass

Result:
run /tmp/candi-bundle-060901586/bootstrap/bootstrap.sh: execute on remote: exit status 127

### Logs

```shell
┌ ⛵ ~ Bootstrap: Cluster UUID
│ Cluster UUID from cache: da576888-b72a-4dc8-8a6d-dd8ea3b12569
└ ⛵ ~ Bootstrap: Cluster UUID (0.00 seconds)

┌ ⛵ ~ Bootstrap: Wait for SSH on Master become Ready
│ ┌ Connection string
│ │ ssh test34@example.com
│ └ Connection string (0.00 seconds)
│ 
│ ┌ Waiting for SSH connection
│ │ Try to connect to example.com host
│ │ 🎉 Succeeded!
│ └ Waiting for SSH connection (1.28 seconds)
└ ⛵ ~ Bootstrap: Wait for SSH on Master become Ready (2.28 seconds)

┌ ⛵ ~ Bootstrap: Detect Bashible Bundle
│ Detected bundle: debian
└ ⛵ ~ Bootstrap: Detect Bashible Bundle (3.05 seconds)

┌ ⛵ ~ Bootstrap: Rendered templates directory
│ /tmp/candi-bundle-451750384
└ ⛵ ~ Bootstrap: Rendered templates directory (0.00 seconds)

┌ ⛵ ~ Bootstrap: Initial bootstrap
│ ┌ Render bootstrap templates
│ │ From "/deckhouse/candi/bashible/bundles/debian" to "/bootstrap"
│ │ From "/deckhouse/candi/cloud-providers/bashible/bundles/debian" to "/bootstrap"
│ │ Templates directory "/deckhouse/candi/cloud-providers/bashible/bundles/debian" does not exist. Skipping...
│ │ From "/deckhouse/candi/cloud-providers/bashible/common-steps" to "/bootstrap"
│ │ Templates directory "/deckhouse/candi/cloud-providers/bashible/common-steps" does not exist. Skipping...
│ └ Render bootstrap templates (0.00 seconds)
│
│ ┌ bootstrap.sh
│ └ bootstrap.sh (3.07 seconds) FAILED
└ ⛵ ~ Bootstrap: Initial bootstrap (3.08 seconds) FAILED

run /tmp/candi-bundle-451750384/bootstrap/bootstrap.sh: execute on remote: exit status 127
```

**Comment by konstantin-axenov** [comment] 2022-11-02 11:20
The root cause of the problem is that deckhouse-controller version mismatch dhctl version. This is kind of bug that we allow it.

**Comment by deckhouse-BOaTswain** [comment] 2023-03-03 09:38
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by nabokihms** [comment] 2023-03-07 13:52
This issue will be fixed in the scope of this pr https://github.com/deckhouse/deckhouse/issues/41
I'm closing the current one. Please, open another issue if you still has a problem ✋

**Closed by nabokihms** 2023-03-07 13:52 UTC
Labels: priority/backlog, source/community, status/needs-triage
