### ISSUE TITLE
[dhctl] Add /deckhouse/version to installation image

### ISSUE THREAD

**Issue by gyrter** [deckhouse/deckhouse#2920] opened 2022-10-31 10:51 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It is difficult to determine version of installed deckhouse distribution for new users. Install image `deckhouse/ce/install` does not contain any version information for installer.

### Proposed Solution

Add `/deckhouse/version` file or file with a version matrix with the name of channels and the version of deckhouse.

**Comment by dezzzm** [comment] 2022-10-31 10:58
Please add the correct version display in dhctl  ( registry.deckhouse.io/deckhouse/ce/install:v1.38.4 )
```
[deckhouse] root@81dba7c784f2 / # dhctl --version
v0.0.0
[deckhouse] root@81dba7c784f2 / # dhctl version
dhctl dev
```

**Comment by yalosev** [comment] 2022-10-31 12:30
```
cat /deckhouse/version
```
inside the deckhouse container will show the version
but anyway `dhctl version` should also be fixed

**Comment by nabokihms** [comment] 2022-11-01 13:43
Seems like a duplicate of https://github.com/deckhouse/deckhouse/issues/41

**Comment by gyrter** [comment] 2022-11-03 07:10
Yeap. It looks like duplicate, but this issue have some additional features and the solution in PR's.

**Comment by nabokihms** [comment] 2023-01-31 07:52
Merged

**Closed by nabokihms** 2023-01-31 07:52 UTC
Labels: type/enhancement, area/cli, priority/backlog, source/community
