### ISSUE TITLE
[prometheus] CronJobFailed alert is not firing

### ISSUE THREAD

**Issue by Beastlex** [deckhouse/deckhouse#6669] opened 2023-11-27 10:03 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.54.5

### Expected Behavior

Version of kubernetes is 1.25.15. When a CronJob execution fails, we expect to see the _CronJobFailed_ alert in _Prometheus_.

### Actual Behavior

Version of kubernetes is 1.25.15. When a CronJob execution fails, there is not any _CronJobFailed_ alert in _Prometheus_.

### Steps To Reproduce

1. Install Deckhouse v1.54.5 with kubernetes 1.25.15
2. Create CronJob which will failed with
_kubectl apply -f_ 
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-fail-job
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fail-container
            image: busybox
            command: ["sh", "-c", "exit 1"] # always exit with non-zero code
          restartPolicy: Never
      backoffLimit: 2
```
3. Check alerts in cluster with
`kubectl get clusteralerts.deckhouse.io`
or in Prometheus' Alerts Tab

**Comment by scaps1** [comment] 2024-10-18 11:02
Hello!
Unfortunately I can't reproduce your bug. I used your CronJob
Current environment:
K8s - 1.27.16
Deckhouse - 1.64.3
```
[okmeter] root@fsn-dev-kube-master01:~# kubectl describe cronjobs.batch test-fail-job -n d8-monitoring
Name:                          test-fail-job
Namespace:                     d8-monitoring
Labels:                        <none>
Annotations:                   <none>
Schedule:                      */5 * * * *
Concurrency Policy:            Allow
Suspend:                       False
Successful Job History Limit:  3
Failed Job History Limit:      1
Starting Deadline Seconds:     <unset>
Selector:                      <unset>
Parallelism:                   <unset>
Completions:                   <unset>
Pod Template:
  Labels:  <none>
  Containers:
   fail-container:
    Image:      busybox
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
      exit 1
    Environment:     <none>
    Mounts:          <none>
  Volumes:           <none>
Last Schedule Time:  Fri, 18 Oct 2024 13:55:00 +0300
Active Jobs:         test-fail-job-28820815
Events:
  Type    Reason            Age                    From                Message
  ----    ------            ----                   ----                -------
  Normal  SuccessfulCreate  50m                    cronjob-controller  Created job test-fail-job-28820765
  Normal  SawCompletedJob   49m                    cronjob-controller  Saw completed job: test-fail-job-28820765, status: Failed
```
```
[okmeter] root@fsn-dev-kube-master01:~# kubectl get clusteralerts.deckhouse.io
NAME               ALERT                   SEVERITY   AGE     LAST RECEIVED   STATUS
df8dacc517c9c958   CronJobFailed           5          4m8s    38s             firing
```

**Comment by vladimirGuryanov** [comment] 2024-10-26 21:21
In the current version of Deckhouse 1.64, the issue is not reproduced. However, we have found another case where the CronJob doesn't work and we don't receive alerts. This has been fixed in PR

**Closed by vladimirGuryanov** 2024-10-26 21:21 UTC
Labels: area/monitoring, type/bug, source/internal-client
