### ISSUE TITLE
deckhouse: change-registry helper unauthorized problems

### ISSUE THREAD

**Issue by kusaleev** [deckhouse/deckhouse#8776] opened 2024-06-24 14:09 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.58.10

### Expected Behavior

If images layer doesn't exist in a private registry error message is "not found", not "unauthorized".

### Actual Behavior

When changing the image storage to a private one, deck house searches for the image of the current version (which is installed in the cluster). This image is not in the image storage (not loaded), an unauthorized error appears.

### Steps To Reproduce

1. Privite registry - Harbor (Version v2.11.0-70255684)
2. Deckhouse was installed by 1.58.10 version
3. Disabled releaseChannel, update.mode - disabled
4. Upload release from 1.60.6 to private registry
5. Change registry by official instruction - https://deckhouse.io/documentation/v1/deckhouse-faq.html#how-do-i-switch-a-running-deckhouse-cluster-to-use-a-third-party-registry
6. Having a problem (see logs section)

### Additional Information

Authorization for private registry works correctly (was checking by docker login).

Command to reproduce (host, user and password was changed):
```
> kubectl exec -n d8-system deploy/deckhouse -c deckhouse -- bash -c "echo '$CA_CONTENT' > /tmp/ca.crt && deckhouse-controller helper change-registry --ca-file /tmp/ca.crt --user '*****' --password '*****' $HARBORHOST:8082/d8/dist/"
```

### Logs

```shell
Output for command:


time="2024-06-24T13:04:40Z" level=info msg="Kubernetes client is configured successfully with 'out-of-cluster' config" operator.component=KubernetesAPIClient
time="2024-06-24T13:04:40Z" level=info msg="Retrieving deckhouse deployment..." operator.component=ChangeRegistry
deckhouse-controller: error:
image 'HARBORHOST:8082/d8/dist/@sha256:79ed551f4d0ec60799a9bd67f35441df6d86443515dd8337284fb68d97a01b3d' doesn't exist: GET https://HARBORHOST:8082/v2/d8/dist//manifests/sha256:79ed551f4d0ec60799a9bd67f35441df6d86443515dd8337284fb68d97a01b3d: UNAUTHORIZED: unauthorized to access repository: d8/dist, action: pull: unauthorized to access repository: d8/dist, action: pull, try --help
command terminated with exit code 1
```
```

**Comment by mvasl** [comment] 2024-07-30 13:33
The issue is not reproducible in current main builds, so I'm closing the issue.

**Closed by mvasl** 2024-07-30 13:33 UTC
Labels: type/bug, source/deckhouse-team
