### ISSUE TITLE
ServiceMonitors for Grafana and Prometheus do not get created

### ISSUE THREAD

**Issue by Nitive** [deckhouse/deckhouse#154] opened 2021-09-10 09:27 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.24.16

### Expected Behavior

After cluster setup and connecting to Alertmanager there are 3 false-positive alerts: D8PrometheusLongtermTargetAbsent, D8GrafanaTargetAbsent and D8TricksterTargetAbsent. This happens because ServiceMonitors for the services do not get created. I far as I understand this is because they are part of [flant-edition](https://github.com/deckhouse/deckhouse/tree/main/ee/fe/modules) (btw I thought it means “free-edition” for a long time 🙂)

I expect either ServiceMonitors should be created or no alert rules should be created as part of CE/EE installation

### Actual Behavior

There are false-positive alerts because of metrics absence

### Steps To Reproduce

1. Setup EE Deckhouse cluster (I haven't tested CE)
2. Run `kubectl get servicemonitor -n d8-monitoring`
3. No service monitors for Prometheus, Grafana and Trickster

### Workaround

Create service monitors. **Most likely, this will lead to deckhouse update errors when the fix is released**

```
kubectl apply -f https://gist.githubusercontent.com/Nitive/766d221075f6deb4b735c291d8d2dcbb/raw/7c797bec0ad23accda7cf857ef05d0c663e248e0/deckhouse-service-monitors.yaml
```

**Comment by nabokihms** [comment] 2021-09-10 09:53
The problem is that monitors for Prometheus and Grafana are included in the [monitoring applications](https://github.com/deckhouse/deckhouse/tree/v1.24.16/ee/fe/modules/340-monitoring-applications) module, which has been considered experimental.

As an intermediate solution, we can create monitors in the Prometheus module only if the monitoring applications module is disabled.

**Comment by nabokihms** [comment] 2021-09-15 12:01
Fixed in https://github.com/deckhouse/deckhouse/commit/bb47d9240b9357f6fdb45c172ef179842053fc95

**Closed by nabokihms** 2021-09-15 12:01 UTC
Labels: area/monitoring, type/bug
