### ISSUE TITLE
[candi] bootstrap nodes

### ISSUE THREAD

**Issue by kirill-kashin** [deckhouse/deckhouse#7853] opened 2024-03-20 16:26 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

when bootstrap a node, if registry passes in headers
bearer realm instead of Bearer realm.
 header: www-authenticate: bearer realm="https://docker-proxy.registry/v2/token",service="docker-proxy.registry"
then we will get an error, because [code](https://github.com/deckhouse/deckhouse/blob/086dd666dc5de749d6cf268f9f2644ba5d18c1d3/candi/bashible/bundles/centos/bootstrap.sh.tpl#L90) is fetching Bearer realm.
```
bb-exit [ERROR] couldn't find bearer realm parameter, consider enabling bearer token auth in your registry, returned header
```

### Proposed Solution

add the -i flag to grep
`
grep -oiE 'Bearer realm'
`

**Comment by konstantin-axenov** [comment] 2024-04-15 09:41
Duplicate of https://github.com/deckhouse/deckhouse/issues/7593

**Closed by konstantin-axenov** 2024-04-15 09:41 UTC
Labels: type/enhancement, status/needs-triage
