### ISSUE TITLE
Dashboard throughs only errors after installation and Unauthorized

### ISSUE THREAD

**Issue by smilebasti** [deckhouse/deckhouse#178] opened 2021-09-15 11:16 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.0.0

### Expected Behavior

After opening the Kubernetes Dashboard all options should be visible.

### Actual Behavior

After the Installation following the Bare-Metal Guide on the website i got this error on the Dashboard:

![image](https://user-images.githubusercontent.com/60941345/133421752-fa8e217c-ceb0-41e6-8928-65c62ec7d045.png)

I thought maybe a reboot could solve that issue. After that i tried to access the Dashboard again and i was able to log in but now the bell in the corner only says:
Unauthorized

Every other application (Grafana, status etc. are working fine)

### Steps To Reproduce

Following this guide: https://deckhouse.io/en/gs/bm/step6.html

### Logs

```shell
Dashboard logs:
2021/09/15 10:57:39 [2021-09-15T10:57:39Z] Outcoming response to 89.1.213.176 with 200 status code
2021/09/15 10:57:44 [2021-09-15T10:57:44Z] Incoming HTTP/1.1 GET /api/v1/namespace request from 89.1.213.176:
2021/09/15 10:57:44 Getting list of namespaces
2021/09/15 10:57:44 Non-critical error occurred during resource retrieval: Unauthorized
2021/09/15 10:57:44 [2021-09-15T10:57:44Z] Outcoming response to 89.1.213.176 with 200 status code
2021/09/15 10:57:46 Getting application global configuration
2021/09/15 10:57:46 Application configuration {"serverTime":1631703466111}
2021/09/15 10:57:49 [2021-09-15T10:57:49Z] Incoming HTTP/1.1 GET /api/v1/namespace request from 89.1.213.176:
2021/09/15 10:57:49 Getting list of namespaces
2021/09/15 10:57:49 Non-critical error occurred during resource retrieval: Unauthorized
2021/09/15 10:57:49 [2021-09-15T10:57:49Z] Outcoming response to 89.1.213.176 with 200 status code
2021/09/15 10:57:50 [2021-09-15T10:57:50Z] Incoming HTTP/1.1 GET /api/v1/namespace request from 89.1.213.176:
2021/09/15 10:57:50 Getting list of namespaces
2021/09/15 10:57:50 Non-critical error occurred during resource retrieval: Unauthorized
```

**Comment by nabokihms** [comment] 2021-09-15 11:58
Hello, @smilebasti. Thank you for reporting.

According to the provided info, kubernets apiserver does not accept the user's token. Could you check the kube-apiserver logs in the kube-system namespace and post them to this thread?

**Comment by smilebasti** [comment] 2021-09-15 12:15
`E0915 12:13:02.743837       1 oidc.go:224] oidc authenticator: initializing plugin: Get "https://dex.k8s.replaced-domain.com/.well-known/openid-configuration": x509: certificate signed by unknown authority
I0915 12:13:02.769300       1 client.go:360] parsed scheme: "passthrough"
I0915 12:13:02.769444       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://192.168.20.214:2379  <nil> 0 <nil>}] <nil> <nil>}
I0915 12:13:02.769498       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
E0915 12:13:03.995108       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, oidc: authenticator not initialized]
E0915 12:13:04.493988       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, oidc: authenticator not initialized]
`

**Comment by nabokihms** [comment] 2021-09-15 13:50
So, the problem is that kube-apiserver could not validate that token is signed by Dex.
1. Could you show the certificate from the `https://dex.k8s.replaced-domain.com/.well-known/openid-configuration`? It is easy to get by using the `openssl` tool.
2. Could you provide the kube-apiserver manifest from the `/etc/kubernetes/manifests` folder?

**Comment by smilebasti** [comment] 2021-09-15 14:54
[kube-apiserver.txt](https://github.com/deckhouse/deckhouse/files/7170962/kube-apiserver.txt)

Openssl shows my the Let'sEncrypt certificate that my reverse proxy gave it. Without it, it only shows a localhost/selfsigned certificate.

**Comment by nabokihms** [comment] 2021-09-16 10:38
The problem is that kube-apiserver cannot validate IdP certificate with the CA certificate provided by the following path.
```
--oidc-ca-file=/etc/kubernetes/deckhouse/extra-files/oidc-ca.crt
```

1. From kube-apiserver pod, Dex domain should resolve in the internal Dex cluster ip address (there is a corresponding entry in the /etc/hosts file inside the pod). 
2. Dex itself listens using a tls certificate signed by kubernetes CA. 
3. There should be a Kubernetes CA in `/etc/kubernetes/deckhouse/extra-files/oidc-ca.crt`.

Could you give me feedback about these three points? Are all of them true for your cluster?

**Comment by smilebasti** [comment] 2021-09-16 16:04
1.  the file shows additional to the domains and ip's i added in step 5.
# Entries added by HostAliases.
10.222.145.54   dex.k8s.domain.com

2.  Where can i find that
3.  Thats there

**Comment by nabokihms** [comment] 2021-12-20 21:20
I managed to find the problem. It seems that you have entries in the `/etc/hosts` file on a master node. It prevents kube-apiserver from resolving dex domain properly. 

There is another issue opened to track the progress.
If you don't mind, I will close this one in favor of https://github.com/deckhouse/deckhouse/issues/329

**Closed by nabokihms** 2021-12-20 21:20 UTC
Labels: type/bug, area/ux
