### ISSUE TITLE
[cloud-provider-aws] Hook doesn't match NG template with more than one with same key:effect

### ISSUE THREAD

**Issue by Beastlex** [deckhouse/deckhouse#7141] opened 2024-01-15 13:15 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.56.5

### Expected Behavior

1. In cluster with AWS cloud provider create NodeGroup with 
```
nodeTemplate:
    ...
    taints:
    - effect: NoExecute
      key: dedicated
      value: production
    - effect: NoExecute
      key: dedicated
      value: static
```
2. Nodes in NG become ready and CSI will deployed on them

### Actual Behavior

Node stuck

**Comment by konstantin-axenov** [comment] 2024-01-18 07:53
Duplicate of https://github.com/deckhouse/deckhouse/issues/7142

**Closed by konstantin-axenov** 2024-01-18 07:53 UTC
Labels: area/cloud-provider, type/bug, status/needs-triage
