### ISSUE TITLE
[log-shipper] Alert if destination rejects logs

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#3663] opened 2023-01-27 15:31 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Users want to get alert if logs can't be delivered.

### Proposed Solution

Add alert.

### Additional Information

```
2023-01-27T13:07:47.390065Z  WARN sink{component_kind="sink" component_id=destination/cluster/loki-storage component_type=loki component_name=destination/cluster/loki-storage}:request{request_id=12}: vector::sinks::util::retries: Retrying after error. error=Server responded with an error: 429 Too Many Requests
2023-01-27T14:07:47.655208Z  WARN sink{component_kind="sink" component_id=destination/cluster/loki-storage component_type=loki component_name=destination/cluster/loki-storage}:request{request_id=12}: vector::sinks::util::retries: Retrying after error. error=Server responded with an error: 429 Too Many Requests
```

**Comment by nabokihms** [comment] 2023-01-27 16:07
Related https://github.com/deckhouse/deckhouse/pull/3149

**Comment by EvgenySamoylov** [comment] 2023-01-29 20:54
Looks like a duplicate of #3118

**Closed** 2023-02-01 11:27 UTC
Labels: type/enhancement, source/internal-client, area/logs
