### ISSUE TITLE
[aws] Support per-AZ NAT

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#4020] opened 2023-03-07 13:14 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Currently, we deploy only one NAT. This is not ideal, but we can't do otherwise, since AWS CCM manages only one route table. And each route table can manage only one default route.

### Proposed Solution

Enhance AWS CCM so it can manage multiple route tables that point to NAT GW in multie AZs.

**Comment by nabokihms** [comment] 2023-03-07 13:23
Duplicate of https://github.com/deckhouse/deckhouse/issues/247

**Closed by nabokihms** 2023-03-07 13:23 UTC
Labels: area/cloud-provider, type/enhancement, status/needs-triage
