### ISSUE TITLE
[upmeter]  upmeter-probe-controller-manager is not removed for a long time 

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#6672] opened 2023-11-27 11:28 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.54.5

### Expected Behavior

tests should not stay for long

### Actual Behavior

upmeter-probe-controller-manager sometimes stays and is not removed.
new upmeter-probe-controller-managers are created in parallel.

### Logs

```shell
upmeter-probe-controller-manager-acebfbff   0/1     3d12h
```

**Comment by konstantin-axenov** [comment] 2023-11-30 12:12
Closed as duplicate of https://github.com/deckhouse/deckhouse/issues/6672

**Closed by konstantin-axenov** 2023-11-30 12:12 UTC
Labels: type/bug, status/needs-investigation, source/internal-client

**Comment by alexey-gavrilov-flant** [comment] 2023-11-30 13:32
https://github.com/deckhouse/deckhouse/issues/2327
