### ISSUE TITLE
Add CPU Manager support

### ISSUE THREAD

**Issue by meatuses** [deckhouse/deckhouse#5144] opened 2023-07-06 16:01 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

CPU Manager will enable features like NUMA-aware Memory Manager https://kubernetes.io/docs/tasks/administer-cluster/memory-manager/ etc

### Proposed Solution

Add support for tuning CPU Manager parameters

**Comment by konstantin-axenov** [comment] 2023-07-27 07:56
Duplicate of https://github.com/deckhouse/deckhouse/issues/5330

**Comment by deckhouse-BOaTswain** [comment] 2023-12-07 09:38
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Closed** 2024-01-18 14:28 UTC
Labels: type/enhancement, area/cluster-and-infrastructure, priority/backlog, status/needs-triage
